language: python
sudo: required
dist: bionic
python: 3.7
env:
  - TEST=unit
before_install:
  # Install tor and chutney if doing functional tests
  - if [[ $TEST == functional* ]]; then ./test/scripts/install-tor.sh; fi
  - if [[ $TEST == 'functional_v2' ]]; then source test/scripts/install-chutney-v2.sh; fi
  - if [[ $TEST == 'functional_v3' ]]; then source test/scripts/install-chutney-v3.sh; fi
install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt
script:
  # Tests are run with linters
  - if [[ $TEST == functional* ]];
    then
      source ./test/scripts/run-functional-tests.sh;
    elif [[ $TEST == 'unit' ]];
    then
      source ./test/scripts/run-unit-tests.sh;
    fi
  - sphinx-build -W -b html -d ./docs/_build ./docs ./docs/_build/html
after_success:
  - coveralls
